# HTTP Server
server:
  port: 6060
  context-path: /
# Spring properties
spring:
  application:
    name: wu1g-server-web
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  aop:
    auto: true
    proxy-target-class: true
  resources:
    static-locations: classpath:/static/,file:${wu1g.common.fileServer.rootFolder}
  mvc:
    #表示所有的访问都经过静态资源路径
    static-path-pattern: /**
    view:
      prefix: classpath*:template/
      suffix: .html
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/krpano?serverTimezone=UTC&noAccessToProcedureBodies=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: root
#    # 下面为连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 300000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    #validationQuery: select "1"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

logging:
  config: classpath:logback.xml
#  level:
#    root: INFO
#    com.wu1g: DEBUG
#    com.wu1g.dao: TRACE
mybatis:
  type-aliases-package: com.wu1g.vo
  mapper-locations: classpath*:mybatis/**/*.xml
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
#  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

wu1g:
  config:
    beetl: classpath:/conf/beetl.properties
  krpano:
    win: d:/home/krpano/win/krpanotools64.exe
    linux: /home/wu1g/software/krpano/krpanotools
    mac: /Users/panpan/soft/krpano-1.19-pr8
    config:  makepano -config=templates/vtour-multires.config  -askforxmloverwrite=false -xml=false -html=false -panotype=sphere #-tilesize=256 -adjustlevelsizes=true -adjustlevelsizesformipmapping=true -progressiveloading=auto -preview=true -cspreview=true -quiet=false -maxcubesize=512
  common:
    fileServer:
      rootFolder: /home/wu1g/file/
      upload: ${wu1g.common.fileServer.rootFolder}upload/
      download: /upload/
      image:
        executorServiceSize: 5
        n0:
          width: 200
          height: 200
        n1:
          width: 400
          height: 400
        n2:
          width: 800
          height: 800
        n3:
          width: 1200
          height: 1200
