#定义应用级别的，如果搭配spring-cloud-config使用 application.yml里面定义的文件可以实现动态替换
info:
  description: 文件上传
  version : 1.0
# HTTP Server
server:
  port: 28888
  context-path: /
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/,file:${hsd.common.fileServer.rootFolder}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  aop:
    auto: true
    proxy-target-class: true
  sleuth:
    sampler:
      percentage: 0.1
  zipkin:
    enabled: true
    base-url: http://192.168.108.101:9411
  #rabbitmq:
    #addresses: 192.168.108.100:5672,192.168.108.101:5672,192.168.108.102:5672
    #username: user-dev
    #password: AES:Jdd7GJIx8oXFqMvDfLqEVg==
    #virtualHost: /vhost/dev
    #publisher-confirms: true
  boot:
    admin:
      url: http://192.168.108.100:8889
      routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        url: http://${spring.boot.admin.url}/turbine.stream

eureka:
  user:
    name: admin
    password: admin
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1 # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 2 # 续约更新时间间隔（默认30秒）
  client:
    registryFetchIntervalSeconds: 5 #从eureka服务器注册表中获取注册信息的时间间隔(s),默认为30秒
    registerWithEureka: true #服务注册
    fetchRegistry: true #服务获取
    serviceUrl:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@192.168.108.199:8761/eureka/
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖

logging:
  file: "/mnt/app/${spring.application.name}/logs/log_start.log"

# 自定义配置
hsd:
  common:
    appPrefix: dev_   #指定app前缀（开发中可使用IP），系统在队列名、Cache名等前会自动加上前缀，以便不同环境冲突
    fileServer:
      rootFolder: /mnt/file/
      upload: ${hsd.common.fileServer.rootFolder}upload/
      download: http://192.168.108.199:28890/hsd-file-server/upload/ #/upload/
      image:
        executorServiceSize: 5
        n1:
          width: 200
          height: 200