info:
  description: 应用监控中心
  version : v1.0

server:
  port: 8889
spring:
  application:
    name: hsd-health-server
  boot:
    admin:
      url: http://192.168.101.100:${server.port}
      username: "${security.user.name}"
      password: "${security.user.password}"
#      client:
#        metadata:
#          user.name: "${security.user.name}"
#          user.password:  "${security.user.password}"
      routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        url: http://192.168.101.100:${server.port}/turbine.stream
security:
  basic.enabled: false

  user:
    name: admin
    password: admin

endpoints:
  health:
    sensitive: false
  cors:
    allowed-methods: HEAD,GET,POST

#
logging:
  file: "/logs/${spring.application.name}.log"

management:
  security:
    enabled: false
