info:
  description: 服务链路追踪
  version : v1.0
server:
  port: 9411
  context-path: /
spring:
  application:
    name: hsd-zipkin-server
  boot:
    admin:
      url: http://192.168.101.100:8889
      client:
          metadata:
            user:
              name: ${security.user.name}
              password: ${security.user.password}
      routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        url: http://${spring.boot.admin.url}/turbine.stream
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

management.security.enabled: false

logging:
  file: "/mnt/app/${spring.application.name}/logs/log_start.log"

# 自定义配置
hsd:
  common:
    appPrefix: dev_   #指定app前缀（开发中可使用IP），系统在队列名、Cache名等前会自动加上前缀，以便不同环境冲突