# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

#spring.cloud.config.discovery.enabled: true