server:
  port: 8762

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/
    
eureka:
  server:
    enableSelfPreservation: true
    waitTimeInMsWhenSyncEmpty: 0.1
  instance:
    hostname: 192.168.106.133
    perferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@192.168.106.133:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

