info:
  description: 配置分发
  version : v1.0
server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/yml-config
#        git:
#          uri: http://192.168.108.16/wuxiaogang/hsd-servers.git         # 配置git仓库的地址
#          searchPaths: doc/yml-config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
#          username: wuxiaogang@heshidai.com                         # git仓库的账号
#          password: wuxiaogang                                      # git仓库的密码
#  rabbitmq:
#    addresses: 192.168.108.100:5672,192.168.108.101:5672,192.168.108.102:5672
#    username: user-dev
#    password: AES:Jdd7GJIx8oXFqMvDfLqEVg==
#    virtualHost: /vhost/dev
#    #publisher-confirms: true
logging:
#  config: d:/logback-spring.xml