#定义应用级别的，如果搭配spring-cloud-config使用 application.yml里面定义的文件可以实现动态替换
# HTTP Server
server:
  port: 6062
  context-path: /
spring:
  application:
    name: hsd-account-web-portal
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/,file:${hsd.common.fileServer.rootFolder}
feign:
  name:
    common: hsd-common-server
    account: hsd-account-server

# 自定义配置
hsd:
  common:
    appPrefix: dev_   #指定app前缀（开发中可使用IP），系统在队列名、Cache名等前会自动加上前缀，以便不同环境冲突
    fileServer:
      rootFolder: /home/hsd/file/
      upload: ${hsd.common.fileServer.rootFolder}upload/
      download: /upload/