server:
  port: 28890

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    #metadataMap:
    #  instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:28888/eureka/

hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

---
logging:
  file: logs/wu1g-proxy-server.log
  level:
    ROOT: INFO