#定义应用级别的，如果搭配spring-cloud-config使用 application.yml里面定义的文件可以实现动态替换
info:
  description: 文件上传
  version : 1.0
# HTTP Server
server:
  port: 28888
  context-path: /
spring:
  application:
    name: hsd-file-server
  boot:
    admin:
      url: http://192.168.101.100:8889
#      client:
#          metadata:
#            user.name: ${security.user.name}
#            user.password: ${security.user.password}
      routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        url: http://${spring.boot.admin.url}/turbine.stream

logging:
  file: "/mnt/app/${spring.application.name}/logs/log_start.log"

# 自定义配置
hsd:
  common:
    appPrefix: dev_   #指定app前缀（开发中可使用IP），系统在队列名、Cache名等前会自动加上前缀，以便不同环境冲突
    fileServer:
      rootFolder: d:/home/hsd/file/
      upload: ${hsd.common.fileServer.rootFolder}upload/
      download: /upload/
      image:
        executorServiceSize: 5
        n1:
          width: 200
          height: 200