#定义应用级别的，如果搭配spring-cloud-config使用 application.yml里面定义的文件可以实现动态替换
info:
  description: 文件上传
  version : 1.0
# HTTP Server
server:
  port: 7000
  context-path: /
spring:
  application:
    name: hsd-file-server
  profiles:
    active: dev
  boot:
    admin:
      url: http://192.168.101.100:8889
#      client:
#          metadata:
#            user.name: ${security.user.name}
#            user.password: ${security.user.password}