#定义应用级别的，如果搭配spring-cloud-config使用 application.yml里面定义的文件可以实现动态替换
info:
  description: 文件上传
  version : 1.0
# HTTP Server
server:
  port: 28888
  context-path: /
spring:
  application:
    name: hsd-file-server
  profiles:
    active: dev