spring:
  application:
    name: eureka
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/
server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

