eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:28888/eureka/
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖

hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

---
# HTTP Server
server:
  port: 6060
  context-path: /
logging:
#  file: logs/wu1g-server-web.log
  level:
    ROOT: INFO
