eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    registerWithEureka: true #是否注册自身到eureka服务器(默认为true)
    fetchRegistry: true #是否从eureka服务器获取注册信息(默认为true)
    serviceUrl:
      defaultZone: http://localhost:28888/eureka/ #注册管理器地址 多个逗号分割
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖

hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

---
# HTTP Server
server:
  port: 6060
  context-path: /
logging:
#  file: logs/wu1g-web-server.log
  level:
    ROOT: INFO
