# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

# HTTP Server
server:
  port: 80
  context-path: /
# Spring properties
spring:
  application:
     name: wu1g-services
  mvc:
      view:
        suffix: .html
  datasource:
#    name: cwwyw
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.8.233:3306/kf_cwwyw1
#    username: root
#    password: btol123456

#    url: jdbc:mysql://192.168.8.233:3306/dev_wu1g
#    username: kfuser
#    password: kfuser
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/krpano
    username: root
    password: root
#    # 下面为连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 300000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 600000
#    validationQuery: select 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
#    # 合并多个DruidDataSource的监控数据
#    useGlobalDataSourceStat: true

mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:/mybatis/**/*.xml

configuration:
  mapUnderscoreToCamelCase: true
  callSettersOnNulls: true
  logPrefix: dao.

wu1g:
  common:
    fileServer:
      rootFolder:
        upload: /mnt/app/nginx/html/download/
        download: /download/