server:
  port: 28888

eureka:
  server:
    enable-self-preservation: false # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 4000 # 清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: false #是否注册自身到eureka服务器(默认为true)
    fetchRegistry: false #是否从eureka服务器获取注册信息(默认为true)
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #server:
    #waitTimeInMsWhenSyncEmpty: 0